---
title: "mapa"
author: "Sofia"
date: "20/7/2021"
output: pdf_document
---
```{r}
felicidad <- readr::read_csv("https://raw.githubusercontent.com/cienciadedatos/datos-de-miercoles/master/datos/2019/2019-08-07/felicidad.csv")
```


```{r}
paises <- readr::read_csv("https://gist.githubusercontent.com/kintero/7d1db891401f56256c79/raw/a61f6d0dda82c3f04d2e6e76c3870552ef6cf0c6/paises.csv")
```


```{r}
paises <- select(paises,c("nombre","continente","name"))
paises$continente<- stri_trans_general(paises$continente,"Latin-ASCII")
felicidad$pais <- stri_trans_general(felicidad$pais,"Latin-ASCII")
```


```{r}
paises <- paises %>% 
     mutate(continente = recode(continente, "Australia y Oceanía" = "Oceania"))
```


```{r}
mapa <- inner_join(felicidad, paises, by = c("pais"="name"))
```


```{r}
mapa <- mapa %>%
       rename(region = pais)
```

```{r}
mapa_felicidad <- left_join(mapa_mundo, mapa, by = "region")
```

```{r}
ggplot(mapa_felicidad, aes(long, lat, group = group))+
     geom_polygon(aes(fill = escalera_vida), color = "white")+
     scale_fill_viridis_c()
```

